#!/bin/bash
#
# Stop de Derby server die gestart werd met startDerby
#

# Volgende twee variabelen moeten correct zijn ingesteld (zonder / op het einde)
# Installatiemap van java
export JAVA_HOME=/usr/lib/jvm/jdk-11.0.1+13

# Map waar de Derby-scripts zich bevinden
export DERBY_HOME=/usr/share/derby
#

$DERBY_HOME/NetworkServerControl shutdown -p 45270
