package Oefeningen.ContactsGUI.DatabankAccess.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class JDBCAbstractDAO {
    private Connection connection;

    public JDBCAbstractDAO(Connection connection) {
        this.connection = connection;
    }

    /**
     * Hulpmethode om een prepared statement aan te maken
     */
    protected PreparedStatement prepare(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    protected PreparedStatement prepareAutoGenerated (String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS );
    }

    protected Connection getConnection(){
        return connection;
    }
}
