/* JDBCAbstractDAO.java
 * ============================================================
 * Copyright (C) 2012-2013 Universiteit Gent
 * 
 * Bijlage bij het vak 'Programmeren 2'.
 * 
 * Auteur: Kris Coolsaet
 */

package prog2.contacts.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Abstracte bovenklasse van de JDBC-DAOs
 */
class JDBCAbstractDAO {

    private Connection connection;

    public JDBCAbstractDAO(Connection connection) {
        this.connection = connection;
    }

    /**
     * Hulpmethode om een prepared statement aan te maken
     */
    protected PreparedStatement prepare (String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    /**
     * Hulpmethode om een prepared statement aan te maken met 'autogenerated keys'
     */
    protected PreparedStatement prepareAutoGenerated (String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS );
    }
}
